<%@ Page Language="C#" MasterPageFile="~/client.master" AutoEventWireup="true" CodeFile="Home.aspx.cs" Inherits="Home" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

<br />
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

	<title>wowslider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="wowslider, WOW Slider, Image Slider jQuery, Ui Slider jQuery" />
	<meta name="description" content="wowslider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	
</head>
<body style="background-color:#ffffff">
	<table cellpadding="15" cellspacing="10" align="center">
    <tr>
        <td><asp:Image ID="Image1" runat="server" Height="230px" Width="230px" ImageUrl="images\sk.jpg" /></td>
        <td><asp:Image ID="Image2" runat="server" Height="230px" Width="230px" ImageUrl="images\sk2.jpg" /></td>
        <td><asp:Image ID="Image3" runat="server" Height="230px" Width="230px" ImageUrl="images\sk3.jpg" /></td>
    </tr>
    <tr>
        <td><asp:Image ID="Image4" runat="server" Height="230px" Width="230px" ImageUrl="images\sk4.jpg" /></td>
        <td><asp:Image ID="Image5" runat="server" Height="230px" Width="230px" ImageUrl="images\sk6.jpg" /></td>
        <td><asp:Image ID="Image6" runat="server" Height="230px" Width="230px" ImageUrl="images\images (2).jpg" /></td>
    </tr>
   
</table>

</body>
</html>
</asp:Content>

